[package]
name = "nanowave-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
tokio-tungstenite = "0.28.0"
tungstenite = "0.28.0"
futures-util = "0.3"
url = "2"
anyhow = "1.0.100"